---
title: "Tabooness Survey Results"
output: html_document
---
```{r, echo = F, message = F}
library(knitr)
source('analysis.R')
source('plots.R')

``` 
### Average Tabooness for All 21 Sentences

```{r, echo = F, message = F}
kable(words.avg, 'markdown')
``` 

### Average Tabooness for Specific words

#### Gender
```{r, echo = F, message = F}
kable(gender.avg.word, 'markdown')
gender.word.plot
```

#### Sexuality
```{r, echo = F, message = F}
kable(sexuality.avg.word, 'markdown')
sex.word.plot
```

#### Education
```{r, echo = F, message = F}
kable(edu.avg.word, 'markdown')
edu.word.plot
```

#### English as Primary Language
```{r, echo = F, message = F}
kable(eng.avg.word, 'markdown')
eng.word.plot
```

### Average Tabooness when used in Different contexts
#### Gender
```{r, echo = F, message = F}
kable(gender.avg.cont, 'markdown')
```
#### Sexuality
```{r, echo = F, message = F}
kable(sexuality.avg.cont, 'markdown')
```
#### Education
```{r, echo = F, message = F}
kable(edu.avg.cont, 'markdown')
```
#### English as Primary Language
```{r, echo = F, message = F}
kable(eng.avg.cont, 'markdown')
```